<a href="https://colab.research.google.com/github/juliezousa/portfolio/blob/main/data-structures/Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Define a 5x5 matrix
matrix_5x5 = np.array([
    [2, 4, 6, 8, 10],
    [1, 3, 5, 7, 9],
    [11, 13, 15, 17, 19],
    [12, 14, 16, 18, 20],
    [21, 23, 25, 27, 29]
])

# Calculate determinant using numpy's `linalg` module
determinant_5x5 = np.linalg.det(matrix_5x5)

print(f"Determinant of the 5x5 matrix:\n{matrix_5x5}\nis: {determinant_5x5}")


Determinant of the 5x5 matrix:
[[ 2  4  6  8 10]
 [ 1  3  5  7  9]
 [11 13 15 17 19]
 [12 14 16 18 20]
 [21 23 25 27 29]]
is: 0.0


A determinant of 0 for a matrix has significant implications in linear algebra. It means that the matrix is singular, or in other words, it does not have an inverse.

Here are the key points associated with a determinant being zero:

1. **Non-Invertibility:** For square matrices, a determinant of 0 indicates that the matrix is singular and does not have an inverse. Inverse matrices are crucial in various mathematical operations, and matrices with a determinant of 0 cannot be inverted.

2. **Collinearity or Linear Dependence:** Geometrically, for a transformation represented by a matrix, a determinant of 0 signifies that the transformation collapses the space or squishes it into a lower-dimensional subspace. In the context of vectors, it means that the vectors are linearly dependent or collinear.

3. **Volume Scaling Factor:** For geometric interpretations, the absolute value of the determinant of a matrix represents the scaling factor of the transformation. A determinant of 0 implies that the transformation squashes or collapses the volume of the space to zero.

4. **Solution Spaces:** In systems of linear equations represented by matrices, a determinant of 0 signifies that the system either has infinitely many solutions or no unique solutions at all.

In practical terms, a determinant of 0 often indicates some form of singularity or degeneracy in the matrix, leading to various consequences depending on the context in which the matrix is used, such as in linear systems, transformations, or eigenvalue problems.

In [2]:
# Calculate eigenvalues using numpy's `linalg` module
eigenvalues = np.linalg.eigvals(matrix_5x5)

print(f"Eigenvalues of the 5x5 matrix:\n{eigenvalues}")

Eigenvalues of the 5x5 matrix:
[ 7.36528330e+01+0.00000000e+00j -6.65283303e+00+0.00000000e+00j
 -2.16223131e-15+2.47198129e-15j -2.16223131e-15-2.47198129e-15j
 -7.41394066e-16+0.00000000e+00j]


For a square matrix, eigenvalues can be found even if the determinant is 0. However, a matrix with a determinant of 0 has at least one eigenvalue that is also 0. This happens because the determinant of a matrix is the product of its eigenvalues.

## Transpose matrix



In [4]:
# Define a matrix as a list of lists
matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

# Transpose the matrix using numpy's transpose function
transposed_matrix = np.transpose(matrix)
# Or using .T attribute
# transposed_matrix = matrix.T

print("Original matrix:")
print(matrix)

print("\nTransposed matrix:")
print(transposed_matrix)

Original matrix:
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Transposed matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
